# please create a new token github.com/settings/tokens/new .
# give repo read write and workflow permissions to the token and store its value
# add the token as a repo secret with key GH_TOKEN_1 and value equal to token value stored above

name: Update Readme ascii graph and workflow with random cron interval

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  ratings-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_1 }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install requirements
        run: pip install --upgrade --no-cache-dir -r .github/requirements.txt

      - name: Generate chart
        run: |
          TOKEN=${{ secrets.TOKEN_LICHESS }} python Codes/rating_chart.py > chart.txt

      - run: cat Assets/README-1.md > README.md
      - run: cat chart.txt >> README.md
      - run: cat Assets/README-2.md >> README.md

      - name: Generate workflow yaml
        run: |
          python Codes/generate_random_workflow.py > rating-yaml.txt

      - run: cat rating-yaml.txt > .github/workflows/rating-chart.yml

      - name: Check for changes
        id: changed
        run: git diff --exit-code
        continue-on-error: true

      - name: Commit changes
        if: steps.changed.outcome == 'failure'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Laxman Singh
          author_email: laxmansingh.lakhan@gmail.com
          message: "Auto updating my readme and workflow timing!"
          add: "README.md .github/workflows/rating-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
